### PR TITLE
Weights for electronMVA 2022

### PR DESCRIPTION
**Pull request by Cvico**
Dear reviewers,

This is a PR to include the weights for the newest version of the electron ttHMVA which is to be included in the future Run 3 MC nanoAOD. The weights are included as an xml, just as it was done for the Run 2 version of the MVA.

Best regards,
Carlos Vico

### CODE REVIEW

**Comment by mandrenguyen** [comment]
ping @cms-sw/xpog-l2

**Comment by hqucms** [comment]
+1

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
merge

**Pull request merged**
