### PR TITLE
Add new weights for NanoAOD

### PR DESCRIPTION
**Pull request by arizzi**
- effective areas
- lepton MVAs

### CODE REVIEW

**Comment by arizzi** [comment]
@gpetruc

**Comment by mrodozov** [comment]
follow the changes being tested here: https://github.com/cms-sw/cmsdist/pull/3873

**Comment by arizzi** [comment]
@fabiocos this is needed in the 9_4_AN_X and 9_4_X_

**Comment by fabiocos** [comment]
This has been merged in the master for the time being

**Comment by fabiocos** [comment]
@smuzaffar before moving forward with the next round of 9_4 releases this external need to be merged into the 9_4_X build as well

**Comment by smuzaffar** [comment]
@fabiocos , cms-sw/cmsdist#3875 (for 94X) is merged now.

**Comment by fabiocos** [comment]
@thanks

**Pull request merged**
