### PR TITLE
Updated b-jet and c-jet energy regression weights

### PR DESCRIPTION
**Pull request by peruzzim**
for usage in NanoAOD production starting from v7 campaign

### CODE REVIEW

**Comment by silviodonato** [comment]
@smuzaffar, @mrodozov, @cmsbuild, @fgolf, @santocch, @peruzzim, @tulamor can you please review it and eventually sign? This PR is needed for https://github.com/cms-sw/cmssw/pull/29212

**Comment by smuzaffar** [comment]
+externals

**Comment by silviodonato** [comment]
merge

**Comment by peruzzim** [comment]
+xpog
sorry for not signing this explicitly first

**Comment by smuzaffar** [comment]
@silviodonato , for each cms-data PR, there will be a cms-sw/cmsdist PR too (automatically created once data PR is merged). For example in this case cms-sw/cmsdist#5669 was opened. Without merged cmsdist PR we will not get the new files in IBs. 

For now I have merged cms-sw/cmsdist#5669 and restart the IB

**Comment by silviodonato** [comment]
Thanks @smuzaffar ! I forgot about it. Thanks also for restarting the IB

**Comment by santocch** [comment]
+1

**Comment by peruzzim** [comment]
@smuzaffar @mrodozov @silviodonato could you please backport this also to 10_6_X? it's needed for cms-sw/cmssw#31063

thanks!

**Comment by silviodonato** [comment]
@peruzzim for the PR test of cms-sw/cmssw#31063, you can simply pick cms-data/PhysicsTools-NanoAOD#12 as I did right now. Then, we definitely need a backport of  cms-sw/cmsdist#5669 in https://github.com/cms-sw/cmsdist/tree/IB/CMSSW_10_6_X/gcc700 before merging the PR.

**Comment by mrodozov** [comment]
done

**Pull request merged**
