### PR TITLE
Adding low pt muon MVA weights

### PR DESCRIPTION
**Pull request by peruzzim**
This PR contains weights for an additional muon discriminator to be used in NanoAOD for 10_2_X and UL.
Please include the updated version in 10_2_X, 10_6_X and master integration environments.

(the pull requests using this will appear very soon)

### CODE REVIEW

**Comment by peruzzim** [comment]
could you please prepare pull requests for the 11_0_X, 10_6_X and 10_2_X integration areas, as requested in cms-sw/cmsdist#4984? thank you really much

**Comment by mrodozov** [comment]
+externals

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Comment by fabiocos** [comment]
@peruzzim @mrodozov @smuzaffar I would say that we need a V01-00-05 tag for this package, and a corresponding update of cmsdist in https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_0_X/gcc700/data/cmsswdata.txt right?

**Comment by smuzaffar** [comment]
@fabiocos , done. I do not think we need to re-test the cmsdist. As it just adds a new file so I will the cmsdist PR now.
https://github.com/cms-data/PhysicsTools-NanoAOD/releases/tag/V01-00-05
https://github.com/cms-sw/cmsdist/pull/4995

**Comment by fabiocos** [comment]
@smuzaffar thanks, I agree, I will merge it tonight

**Pull request merged**
