### PR TITLE
Adding ONNX file for FastSim refinement backport for Run 2 DeepJet tagging

### PR DESCRIPTION
**Pull request by sbein**
The added file complements the CMSSW backport https://github.com/cms-sw/cmssw/pull/40828, which implements the FastSim refinement of the DeepJet collections.

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals
 This is backport of https://github.com/cms-data/PhysicsTools-NanoAOD/pull/14  . It adds a new files for 10.6.X, so should be safe to already include in 10.6.X externals

**Comment by sbein** [comment]
Hi @smuzaffar, I just refreshed the model with Moritz's latest onnx file. Can we merge this soon? Thnxs.

**Comment by aandvalenzuela** [comment]
Sorry @perrotta! I though it was already tested by https://github.com/cms-sw/cmssw/pull/40828 (that was already merged three weeks ago).
Should I revert the merge? Sorry for the inconvenience.

**Comment by perrotta** [comment]
> Sorry @perrotta! I though it was already tested by [cms-sw/cmssw#40828](https://github.com/cms-sw/cmssw/pull/40828) (that was already merged three weeks ago). Should I revert the merge? Sorry for the inconvenience.

Ah, ok. Yes, it was tested with #40828, and just forgot while merging that one.
Then, no problem: this merge completes the one of #40828.
Sorry for the noise, and thank you!

**Comment by srimanob** [comment]
Hi @smuzaffar @perrotta @rappoccio @sbein @antoniovilela  

I confuse a bit on this PR and [CMSSW_10_6_35](https://github.com/cms-sw/cmssw/releases/CMSSW_10_6_35). Currently, the production stuck because of missing model, btagDeepFlavRefineNN_CHS.onnx, issue. See [here](https://cms-unified.web.cern.ch/cms-unified/showlog/?search=task_SUS-RunIISummer20UL16NanoAODv9-01231#SUS-RunIISummer20UL16NanoAODv9-01231_0:7002)). However, I see it in
https://github.com/cms-data/PhysicsTools-NanoAOD/tree/CMSSW_10_6_X

Do we somehow miss something? 

Thx.

**Comment by srimanob** [comment]
Ah, I think I know. We need CMSSW_10_6_36, which include Update tag for PhysicsTools-NanoAOD to V01-01-00-01-00 [10_6_X]

**Pull request merged**
