### PR TITLE
Updated lepton MVA weights for NanoAOD v5 and UL

### PR DESCRIPTION
**Pull request by peruzzim**
This PR contains new lepton MVA weights to be used in the next NanoAOD productions, in 10_2_X (v5) and 10_6_X (ultra-legacy).
Please switch both branches to use the updated version of this package, when merged.

@sscruz @fgolf @gpetruc

### CODE REVIEW

**Comment by mrodozov** [comment]
assign analysis

**Comment by smuzaffar** [comment]
@mrodozov , cms-bot now takes care of assigning the categories.

**Comment by peruzzim** [comment]
+xpog

**Comment by fabiocos** [comment]
+1

only new files added, the CMSSW PR is ready to be integrated, so I move forward with the integration of this

**Comment by fabiocos** [comment]
merge

**Comment by smuzaffar** [comment]
+externals

**Comment by santocch** [comment]
+1

**Pull request merged**
