### PR TITLE
Add ONNX model for FastSim DeepJet refinement

### PR DESCRIPTION
**Pull request by wolfmor**
Initial ONNX model file for refining DeepJet discriminators of FastSim CHS jets.

The model has been trained and exported to ONNX with PyTorch version 1.9.0 using opset_version=13.

### CODE REVIEW

**Comment by mandrenguyen** [comment]
+1

**Comment by swertz** [comment]
+1

**Comment by perrotta** [comment]
+1
- New model for https://github.com/cms-sw/cmssw/pull/40553

**Comment by perrotta** [comment]
merge

**Pull request merged**
